Script started on Wed Mar  4 11:38:17 2015

[1;34;40m[[1;33mTs'ai Meng-hsun[0m@pts/0[0m([1;36mIMSLAB[0m)[1;34m][[1;37m~[34m][0m > whoami; pwd
tsaimh
/home/tsaimh
[1;34;40m[[1;33mTs'ai Meng-hsun[0m@pts/0[0m([1;36mIMSLAB[0m)[1;34m][[1;37m~[34m][0m > git config -l
user.name=menghsun
user.email=tsaimh@gmail.com
[1;34;40m[[1;33mTs'ai Meng-hsun[0m@pts/0[0m([1;36mIMSLAB[0m)[1;34m][[1;37m~[34m][0m > git clone https://github.com/menghsun/lab1. git
Cloning into lab1...
warning: You appear to have cloned an empty repository.
[1;34;40m[[1;33mTs'ai Meng-hsun[0m@pts/0[0m([1;36mIMSLAB[0m)[1;34m][[1;37m~[34m][0m > mv[K[K^Dexit

Script done on Wed Mar  4 11:39:13 2015
